### ISSUE TITLE
Minor mathematical error in trunk/book.tex

### ISSUE THREAD

**Issue by guanidene** [AllenDowney/ThinkDSP#1]
On line 454 of trunk/book.tex

```a cosine signal with {\tt offset=pi/2} is identical to a sine```

should change to 

```a sine signal with {\tt offset=pi/2} is identical to a cosine```

or

```a cosine signal with {\tt offset=-pi/2} is identical to a sine```

Kindly forgive me if this is not the correct way to report such issues

**Comment by AllenDowney** [comment]
That's a fine way to report such issues.

This one is fixed now.  Thanks!

1236a9e7892a1e5ab9aea7711273c26f19d3edb8
