### ISSUE TITLE
Convolution theorem in Section 8.4 not correct

### ISSUE THREAD

**Issue by spors** [AllenDowney/ThinkDSP#11]
The convolution theorem in Section 8.4 is not correct. Multiplication of the DFTs of two signals results in the periodic/circular convolution of the two signals. This is why zero-padding is required when one aims at the linear convolution in order to compute the output of a linear-time invariant system. You fill find this in amost any good textbook on DSP or since you also like Jupyter notebooks http://nbviewer.jupyter.org/github/spatialaudio/digital-signal-processing-lecture/blob/master/nonrecursive_filters/fast_convolution.ipynb.

**Comment by AllenDowney** [comment]
At this point in the book I have not yet distinguished linear and circular convolution because the examples haven't required it.  It comes up later, although I don't use the terms.  I will consider adding them.  Thanks!
