### ISSUE TITLE
Obscure "0pt" on the html output

### ISSUE THREAD

**Issue by giumas** [AllenDowney/ThinkDSP#13]
On the output html page: http://greenteapress.com/thinkdsp/html/index.html, there is an "0pt" text before the title. 

Could it come from here: https://github.com/AllenDowney/ThinkDSP/blob/master/book/book.tex#L71 ?
If yes, would an empty field `{}` provide the same result (no indent)?

**Comment by AllenDowney** [comment]
Yes, that solves the problem.  Thanks for the suggestion!
