### ISSUE TITLE
Docstrings for Wave class

### ISSUE THREAD

**Issue by giumas** [AllenDowney/ThinkDSP#14]
The doctring for the `Wave` class might be incomplete since the `ts` parameter is missing: https://github.com/AllenDowney/ThinkDSP/blob/master/code/thinkdsp.py#L596

The docstring states `ys: a "wave array" which is a numpy array of floats.` (https://github.com/AllenDowney/ThinkDSP/blob/master/code/thinkdsp.py#L598), but the function `read_wave` only supports integers: https://github.com/AllenDowney/ThinkDSP/blob/master/code/thinkdsp.py#L112

**Comment by AllenDowney** [comment]
Fixed.  Now most init methods take lists as well as NumPy arrays, and ints or floats.
