### ISSUE TITLE
Period definition

### ISSUE THREAD

**Issue by giumas** [AllenDowney/ThinkDSP#15]
From reading this paragraph: https://github.com/AllenDowney/ThinkDSP/blob/master/book/book.tex#L445, I believe that some confusion might arise for a newbie between `cycle` and `period`. 

What about slightly rephrasing this paragraph to clarify what the definition of `period` is?

**Comment by AllenDowney** [comment]
Good suggestion: I have clarified that paragraph. 0146127840c10e1a060142d200314a425fdc0b46

**Comment by AllenDowney** [comment]
BTW, thanks for several of your suggestions.  I'd like to add you to the contributor list: would you email me the name you would like me to use?

**Comment by giumas** [comment]
You can use the name of my email on splitting the main .tex file using `\input`. Many thanks!
