### ISSUE TITLE
DCT initialization

### ISSUE THREAD

**Issue by giumas** [AllenDowney/ThinkDSP#16]
There could be a minor issue with the `__init__` of the `DCT` class: https://github.com/AllenDowney/ThinkDSP/blob/master/code/thinkdsp.py#L485

It is an exact duplication of the `__init__` of the parent `_SpectrumParent` class: https://github.com/AllenDowney/ThinkDSP/blob/master/code/thinkdsp.py#L156. You could delete it or, in alternative, call the parent initialization (if you prefer to make it more explicit).

**Comment by AllenDowney** [comment]
Fixed b4cd21b

Thanks!
