### ISSUE TITLE
Octave definition and too wide wikipedia links

### ISSUE THREAD

**Issue by giumas** [AllenDowney/ThinkDSP#17]
I believe that the term "octave" should deserve a (simplified?) definition within in the text, since it is commonly used in DSP but not so intuitive for a newbie. For instance, in the part about harmonics: https://github.com/AllenDowney/ThinkDSP/blob/master/book/book.tex#L581 

Furthermore, reading the wikipedia links: https://en.wikipedia.org/wiki/Scientific_pitch_notation  and https://en.wikipedia.org/wiki/Interval_%28music%29 that you added to sections 1.1 and 1.2 might distract the reader from the main target that is, if I well understood, general DSP. What is the value added to the concept of harmonics from knowing that `2200 is approximately C$\sharp$7, which is a major third above A6`(https://github.com/AllenDowney/ThinkDSP/blob/master/book/book.tex#L589)?

**Comment by AllenDowney** [comment]
I added a definition for octave.

I see your point about the links, but I'll leave them for now.

Thanks!
