### ISSUE TITLE
Thinkdsp Realtime microphone and speaker ouput

### ISSUE THREAD

**Issue by Tondy** [AllenDowney/ThinkDSP#21]
Hello Allen

I am working on a project to create a low_pass filter on a microphone input for real time playback, I am using the low pass_filter function from thinkdsp to learn . How could some one add a microphone with realtime audio playback. To have the low pass filter play real time?

**Comment by tvaisanen** [comment]
I think that this might be part of the solution in your case. 
http://python-sounddevice.readthedocs.org/en/0.3.3/#simultaneous-playback-and-recording
