### ISSUE TITLE
Spectrogram slice expects integer

### ISSUE THREAD

**Issue by osunderdog** [AllenDowney/ThinkDSP#25]
Chapter three Spectrogram header.
in wave.make_spectogram I am running into this error:

TypeError: slice indices must be integers or None or have an __index__ method

Looks like wave.split()
expects integer input, but the spectrogram has division which causes i and j to go to float.

because this line is division:
step = seg_length / 2

maybe
step = seg_length//2

??

**Comment by AllenDowney** [comment]
Fixed with commit  75ed0c1
Thank you!
