### ISSUE TITLE
getattr in thinkplot.py Config

### ISSUE THREAD

**Issue by grfiv** [AllenDowney/ThinkDSP#26]
I am using your notebooks with Jupyter 4.2.1 and Python 3.5.2 under Ubuntu Desktop 16.10

The code snippet

```
def Config(**options):
    for name in names:
        if name in options:
            getattr(pyplot, name)(options[name])
```
generates TypeError: 'tuple' object is not callable

The following seems to fix it for me

```
def Config(**options):
    for name in names:
        if name in options:
            try:
                getattr(pyplot, name)(options[name])
            except TypeError:
                setattr(pyplot, name, options[name])
```

**Comment by AllenDowney** [comment]
Thanks for reporting this.  I'll investigate as soon as I get a change.

Can you tell me what parameters you are passing to Config?

**Comment by grfiv** [comment]
http://localhost:8888/notebooks/code/chap02.ipynb

```
signal = thinkdsp.SquareSignal(100)
duration = signal.period*3
segment = signal.make_wave(duration, framerate=10000)
segment.plot()
thinkplot.config(ylim=[-1.05, 1.05], legend=False)
```

**Comment by AllenDowney** [comment]
Huh.  I can't replicate that.

Just for debugging purposes, would you clone a fresh copy of the repo and
run that notebook again?

**Comment by grfiv** [comment]
OK. Started fresh and it does not recur.

**Comment by AllenDowney** [comment]
Good news.  Thanks for following up.
