### ISSUE TITLE
Error when using make_spectrogram

### ISSUE THREAD

**Issue by dotanrs** [AllenDowney/ThinkDSP#36]
#### Steps to reproduce the issue

Run the function with a recent numpy version

#### Expected result

a spectrogram should appear

#### Actual result

error:
TypeError: slice indices must be integers or None or have an __index__ method

#### Additional comments

This can be easily fixed by changing line 937 from
step = seg_length // 2
to
step = int(seg_length // 2)

this is because in the new numpy version a slice index can't be a float, and step, which is a float as the result of a // operation, goes on to be a slice index

(I'm new to open source and didn't know how to create a pull request, so I wrote it here)

**Comment by leonchen417** [comment]
Hey dotanrs 
Thanks for sharing. I faced the same issue when using python 3.
For me (window 10,python 3.5) double slashes (//) do the trick.

**Comment by aryabhatta000** [comment]
**_Excellent!_**
Thank you _dotanrs_ 

First, I tried _modifying the **thinkdsp.py python package file**_, while I was in the Jupyter session with thinkdsp imported, this did not immediately resolve the bug, tried reimporting thinkdsp, still did not work. But later tried loading my Jupyter session again and it gave me results. 

I have taken next step and created a pull request with proposed solution. 
Once again kudos - _dotanrs_.

**Comment by AllenDowney** [comment]
And it is merged.  Thanks again!
