### ISSUE TITLE
IPython.display

### ISSUE THREAD

**Issue by rf-andrade** [AllenDowney/ThinkDSP#41]
I've just started the thinkdsp pdf reading, and it's a very good material, indeed. I'm on the first chapter, and facing an issue that I cannot understand yet.
When I run:
 
`from IPython.display import Audio\
audio = Audio(data=wave.ys, rate=wave.framerate)\
audio`

I get <IPython.lib.display.Audio object>, but no player.

I'm running the code in Spyder, with Anaconda.

**Comment by AllenDowney** [comment]
That should work in Jupyter notebook; not sure about Spyder.

**Comment by zwarshavsky** [comment]
I am having iPython display issues as well. 

From jupyter notebook chapter 1:

![image](https://user-images.githubusercontent.com/21163691/38911830-d096f3a6-429f-11e8-9181-a79ef5f77e1c.png)
