### ISSUE TITLE
file reader

### ISSUE THREAD

**Issue by awinashjaiswal** [AllenDowney/ThinkDSP#51]
Hello AllenDowney,
I was using your module and it is really a fabulous work done by you.
But I am facing a problem like this module can't read the mp3 audio file .
If you are upgrading the module please add more audio file extensions readable.

**Comment by AllenDowney** [comment]
Thanks for this suggestion.  When I wrote the first edition I did not find a library that met my critera and could read MP3 files.

It looks like the options are still not great: https://stackoverflow.com/questions/9458480/read-mp3-in-python-3

The top recommendation is to use a stand-alone application to convert from MP3 to WAV.
