### ISSUE TITLE
pdflatex book [ Makefile:20: recipe for target 'all' failed ]

### ISSUE THREAD

**Issue by aryabhatta000** [AllenDowney/ThinkDSP#54]
**This is when attempting to 'make' within book folder:**

![image](https://user-images.githubusercontent.com/41846481/43942088-890e0f34-9c2b-11e8-8baa-baec40f17984.png)

**This is when attempting to 'make' within code folder.**

![image](https://user-images.githubusercontent.com/41846481/43942207-e78d2b62-9c2b-11e8-92d8-058aecd9c576.png)

**Comment by AllenDowney** [comment]
The first one should work.  Not sure what the problem is.

If you are still interested in compiling the book, let me know.
