### ISSUE TITLE
ts = np.linspace(0, 1, framerate)

### ISSUE THREAD

**Issue by ShmuelBenEzra** [AllenDowney/ThinkDSP#55]
it should be ts = np.linspace(0, 1, framerate+1)
in order to preserve
framerate = 1/(ts[1] - ts[0])
for example in 6.1

**Comment by AllenDowney** [comment]
I will check this out as soon as I can.  Thanks!

**Comment by AllenDowney** [comment]
I went with a slightly different solution:
```
ts = np.linspace(0, 1, framerate, endpoint=False)
```
So I have exactly `framerate` points with spacing `1/framerate`

Thanks!
