### ISSUE TITLE
typo in 7.4 "Synthesis with matrices"

### ISSUE THREAD

**Issue by ShmuelBenEzra** [AllenDowney/ThinkDSP#57]
the equation is written:
A exp{ i Phi0 } . exp{ i 2 pi f t } =A exp{ i 2 pi f t + Phi0 }
but it should:
A exp{ i Phi0 } . exp{ i 2 pi f t } =A exp{ i (2 pi f t + Phi0) }

**Comment by AllenDowney** [comment]
Will fix.  Thanks!
