### ISSUE TITLE
7.6 effiicient analysis

### ISSUE THREAD

**Issue by ShmuelBenEzra** [AllenDowney/ThinkDSP#58]
def analyze2(ys, fs, ts)

N is not defined

**Comment by AllenDowney** [comment]
You are right.  There is a simpler version of this function in the most recent version of the book:

```
def analyze2(ys, fs, ts):
    args = np.outer(ts, fs)
    M = np.cos(PI2 * args)
    amps = np.dot(M, ys) / 2
    return amps
```

No need for `N`, so it avoids the issue.
