### ISSUE TITLE
low_pass filter issues

### ISSUE THREAD

**Issue by simulsys** [AllenDowney/ThinkDSP#59]
Hi Allen,

I am trying to use low_pass() from the book ThinkDSP and I find the subsequent call to the amps of the filtered specrum gives an error: AttributeError: 'NoneType' object has no attribute 'amps'

Does the low_pass function return a new version of the spectrum or do I have to recreate the spectrum via wave? Can you help please?
All I am trying to do is filter the spectrum and then use the amps data?
Cheers,
Andrew.

**Comment by AllenDowney** [comment]
Thanks for letting me know.  I will check this out as soon as I can.

Can you send me a minimal snippet of code that reproduces the error?

**Comment by simulsys** [comment]
Hi Allen,

I fear it was my misinterpretation of the command line insruction in the book? I was following Python convention and instantiating a variable with the result of:
spectrum2 = spectrum.low_pass(cutoff=600, factor=0.01)

I chekd a code snippet form your github online and realized that the spectrum2 variable was superfluous. I now have codeline:
spectrum.low_pass(cutoff=600, factor=0.01)

It seems to work. Apololgies for setting a hare running.
Andrew.
