### ISSUE TITLE
missing latex files

### ISSUE THREAD

**Issue by bmabey** [AllenDowney/ThinkDSP#6]
A number of supporting latex files are not found in the repo making the `make` command not usable (outside your personal machine at least).  Would you mind committing them (e.g. latexonly.tex) to this repo?

**Comment by AllenDowney** [comment]
Ok, I just pushed a bunch of support files.  Would you try again and report
back?

**Comment by bmabey** [comment]
```
! LaTeX Error: File `diagram.tex' not found.
```

**Comment by AllenDowney** [comment]
Fixed d3bca16

**Comment by giumas** [comment]
Similar issue with `diagram2.tex`. The figure `dct1.pdf` is missing too.

**Comment by AllenDowney** [comment]
Added.  I finally tested it by cloning and making, and it looks like everything for the book is there.  Have not tested the code in the same way, yet.
