### ISSUE TITLE
Anaconda distro link update

### ISSUE THREAD

**Issue by xJoyride** [AllenDowney/ThinkDSP#63]
Hiya, 

In section 0.2 of the book (PDF version**), the anaconda distro download link is broken (url was   http://continuum.io/downloads.). Current distro can be found at https://www.anaconda.com/distribution/

Thanks for the book Prof!

**PDF version found at: http://greenteapress.com/thinkdsp/thinkdsp.pdf

**Comment by AllenDowney** [comment]
Will update.  Thanks!
