### ISSUE TITLE
TypeError at use of make_spectrogram

### ISSUE THREAD

**Issue by filipthor** [AllenDowney/ThinkDSP#66]
As the title reads, I have hit a bit of a snub trying the code out. 

Trying to run the code:
import thinkdsp

wave = thinkdsp.read_wave('100475__iluppai__saxophone-weep.wav')
spectrogram = wave.make_spectrogram(seg_length=512)
spectrogram.plot(high=700)

on Python 3.6, resulting in: 
Traceback (most recent call last):
...
  File "/Users/filipthor/PycharmProjects/music/main.py", line 9, in <module>
    spectrogram = wave.make_spectrogram(seg_length=512)
  File "/Users/filipthor/anaconda/lib/python3.6/site-packages/thinkdsp.py", line 943, in make_spectrogram
    segment = self.slice(i, j)
  File "/Users/filipthor/anaconda/lib/python3.6/site-packages/thinkdsp.py", line 897, in slice
    ys = self.ys[i:j].copy()
TypeError: slice indices must be integers or None or have an __index__ method

Any ideas?

**Comment by filipthor** [comment]
"ugly-fixed" it by wrapping i and j with int(), which seems to work

**Comment by AllenDowney** [comment]
In the current version,
```
        step = int(seg_length // 2)
```
so `i` and `j` should already be `int`s.

Maybe you have an older version of thinkdsp.py?

**Comment by AllenDowney** [comment]
I just ran a test with current version and all is well.
