### ISSUE TITLE
Python 3 Compatability

### ISSUE THREAD

**Issue by lpashwin** [AllenDowney/ThinkDSP#7]
Are there any plans to make these codes compatible with Python3?

**Comment by AllenDowney** [comment]
Absolutely.  Many of them already are.  I will check for full compatibility
soon.

**Comment by lpashwin** [comment]
Will look forward to it!

**Comment by jolespin** [comment]
As am I considering I decided to make the switch to 3 for getting my new laptop.  This resource looks amazing!

**Comment by AllenDowney** [comment]
I've made a pass through the .py and .ipynb files and everything seems to be working in Python 3.

If you get a chance to try it out, let me know if you run into any problems.

**Comment by jolespin** [comment]
Sorry, i'm having trouble installing this with pip or conda. I've tried `pip install think-dsp` `pip install thinkdsp` same with conda . What's the best way to install this for Python3?

**Comment by AllenDowney** [comment]
@jolespin It's not available as an installable package (yet).  Readers usually clone the repo and then run code in the same directory as thinkdsp.py

It is on my TODO list to make a package that installs all of the ThinkX libraries.
