### ISSUE TITLE
fb.csv and FB.csv lead to duplicate file error on windows and modified state of fb.csv right after cloning. 

### ISSUE THREAD

**Issue by RonaldAJ** [AllenDowney/ThinkDSP#73]
![afbeelding](https://user-images.githubusercontent.com/22000954/95461867-04ba2b80-0977-11eb-8df5-3751b88c8601.png)

**Comment by marksweiss** [comment]
I attempted to fix this in [this PR](https://github.com/AllenDowney/ThinkDSP/pull/77) but this PR created new renamed files and changed all references to use the new names, but still kept the old name-clashing files in the repo. A second PR [here](https://github.com/AllenDowney/ThinkDSP/pull/78/files) removes the old files, which should actually resolve this issue. cc @AllenDowney

**Comment by RonaldAJ** [comment]
Problem is solved! Tested on windows10 creating a fresh clone.

**Comment by marksweiss** [comment]
👍
