### ISSUE TITLE
fractions.gcd() is replaced by math.gcd() in python3.5

### ISSUE THREAD

**Issue by horizonl** [AllenDowney/ThinkDSP#79]
I encountered import error in the chap01.ipynb, based on the [bug tracer](https://bugs.python.org/issue39350), fractions.gcd() is replaced by math.gcd(). 
I change 'fractions' to 'math' in thinkdsp.py line 19 , error gone.

**Comment by AllenDowney** [comment]
Turns out I'm not using `gcd` anyway.  I will remove this import.

Thanks for letting me know!
