### ISSUE TITLE
Missing Python File

### ISSUE THREAD

**Issue by ptracton** [AllenDowney/ThinkDSP#8]
I populated from your tree tonight (1/4/2016) and ran the Makefile in the code directory.  I  received the following error:

python: can't open file 'violin.py': [Errno 2] No such file or directory

violin.py is not in the code directory.  Can you please check it in?

**Comment by AllenDowney** [comment]
Will do.

**Comment by AllenDowney** [comment]
Fixed 6623c8d7d094a1823d371c4bf70cd1169689d9e6
